### ISSUE TITLE
Unused argument repr= repr

### ISSUE THREAD

**Issue by vspinu** [jlmelville/rnndescent#2]
I am seeing the following error no matter what metric I use:

```
> X <- matrix(runif(1000), 100, 10)
> graph <- brute_force_knn(X, k = 20, metric = "euclidean")
> nn <- graph_knn_query(X, X, graph, metric = "euclidean")
Error in Matrix::sparseMatrix(i = rep(1:n_row, times = n_nbrs), j = as.vector(idx),  : 
  unused argument (repr = repr)
Backtrace:
    ▆
 1. └─rnndescent::graph_knn_query(X, X, graph, metric = "euclidean")
 2.   └─rnndescent:::graph_to_list(reference_graph)
 3.     └─rnndescent:::graph_to_rsparse(graph)
 4.       └─rnndescent:::graph_to_sparse(graph, "R")
> 
```

**Comment by vspinu** [comment]
This comes from older version of Matrix package which is the default on R 4.0.0 which I have. It would be good to add an explicit version dependency for matrix package (>= 1.3-4) or something.

**Comment by jlmelville** [comment]
Thanks for pointing this out. Looks like `repr` [was added](https://cran.r-project.org/web/packages/Matrix/news.html) in `1.3.0`.

**Comment by jlmelville** [comment]
This is probably fixed with the obvious change in the `DESCRIPTION`, but I admit I didn't test it.

**Comment by jlmelville** [comment]
Please re-open if this isn't actually fixed.
